# Generated by Django 4.0.4 on 2023-12-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='cargo_num',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
